steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/deeplearning-platform-release/pytorch-gpu', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/deeplearning-platform-release/pytorch-gpu']